---
title: "Analysis - immune cells - microenvironment datasets"
subtitle: "Zoom in immune cells - analysis"
author: "Pernelle"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: show
    code_download: true
    toc: true
    toc_float: true
    number_sections: false
---

<style>
body {
text-align: justify}
</style>

```{r clean, echo = FALSE}
rm(list = ls())
```

<!-- Automatically computes and prints in the output the running time for any code chunk -->
```{r, echo=FALSE}
# https://github.com/rstudio/rmarkdown/issues/1453
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (isFALSE(options[[paste0("fold_", type)]])) return(res)
    
    paste0(
      "<details><summary>", "show", "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot"),
  time_it = local({
    now = NULL
    function(before, options) {
      if (options$time_it) {
        if (before) {
          now <= Sys.time()
        } else {
          res = difftime(Sys.time(), now, units = "secs")
          paste("(Time to run :", round(res, digits = 2), "s)")
        }
      }
    }
  })
)
```

<!-- Set default parameters for all chunks -->
```{r, setup, include = FALSE}
set.seed(1337L)
knitr::opts_chunk$set(echo = TRUE, # display code
                      # display chunk output
                      message = FALSE,
                      warning = FALSE,
                      fold_output = FALSE, # usefull for sessionInfo()
                      fold_plot = FALSE,
                      
                      # figure settings
                      fig.align = 'center',
                      fig.width = 20,
                      fig.height = 15,
                      
                      # something about seed, chunk and Rmarkdown compilation
                      # https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script
                      # cache = TRUE,
                      cache.lazy = FALSE, 
                      
                      # add runtime after chunk
                      time_it = FALSE)
```


```{r library}
library(dplyr)
library(patchwork)
library(ggplot2)
library(org.Mm.eg.db)
library(ComplexHeatmap)
```


# Preparation

In this section, we set the global settings of the analysis. We will store data there :

```{r out_dir}
save_name = "IC"
out_dir = "."
```


We load the dataset :

```{r load_sobj}
sobj = readRDS(paste0(out_dir, "/../6_immune_cell_annotation/","IC_sobj.rds"))
sobj
```

and sample information :

```{r load_sample_info}
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "env_metadata_sample_info.rds"))
sample_info
```

This is the projection of interest :

```{r name2D}
name2D = "harmony_47_umap"
```

We visualize clusters :


```{r clustering, fig.width = 6, fig.height = 4, eval = TRUE}
IC_markers = list("T cells" = c("Cd3g", "Cd3d", "Cd3e", "Cd8a", "Cd4", "Foxd3"),
                  "Macrophages" = c("Mrc1", "Pf4", "Apoe","Gas6","Adgre1"),
                  "Dendritic cells" = c("Plbd1","Cd209a", "Mgl2","Cd74"),
                  "Mast cells" = c( "Kit"),
                  "Langerhans cells" = c("Mfge8","Cd207","H2-M2","Epcam","Pxdc1","Cd74"),
                  "NK cells" = c("Nkg7", "Klrk1", "Klri2", "Klrc2", "Klrb1c", "Ncr1", "Klrb1f"))

# Not found in slot data:
# "Neutrophils" = c("S100a8", "S100a9","Retnlg"))

length(IC_markers)

color_markers_IC = aquarius::c30_palette[c(1:length(IC_markers))]
names(color_markers_IC) = names(IC_markers)

Seurat::DimPlot(sobj, reduction = name2D, label = FALSE, pt.size=0.1, group.by = "IC_cluster_type", cols = color_markers_IC) +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 1)
```

```{r split_dimplot, fig.width = 21, fig.height = 12}

Seurat::DimPlot(sobj, reduction = name2D, group.by ="IC_cluster_type", split.by = "sample_type", label = FALSE,  pt.size = 0.1, cols = color_markers_IC) +
  Seurat::NoLegend() +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 0.8)
```



```{r IC_markers, fig.width = 21, fig.height = 12, eval = FALSE}
#all T cells
Seurat::FeaturePlot(sobj, features =c("Cd3g", "Cd3d", "Cd3e", "Cd8a", "Cd4", "Foxp3"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# Treg markers
Seurat::FeaturePlot(sobj, features =c("Cd4", "Foxp3", "Il2ra"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# gamma delta T cells markers
Seurat::FeaturePlot(sobj, features =c("Cd4", "Cd8a", "Cdh1"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# Mastocytes
Seurat::FeaturePlot(sobj, features =c("Kit","Gata2","Tpsab1"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

Seurat::FeaturePlot(sobj, features =c("Mrc1", "Pf4", "Apoe","Gas6","Adgre1"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# Neutrophils => no neutrophils
Seurat::FeaturePlot(sobj, features =c("Cd14","Csf3r","S100a8","S100a9"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# NK cells (from a paper)
Seurat::FeaturePlot(sobj, features =c("Gzma","Gzmb","Klra7","Klra8","Ncr1"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# NK cells (from Audrey's markers)
Seurat::FeaturePlot(sobj, features =c("Nkg7", "Klrk1", "Klri2", "Klrc2", "Klrb1c", "Ncr1", "Klrb1f"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

# Macrophages (from a paper)
Seurat::FeaturePlot(sobj, features =c("Adgre1","Itgam","Ms4a7","C1qc","Plac8","Ly6c2"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)


# M/B (from a paper)
Seurat::FeaturePlot(sobj, features =c("Gata2","Ms4a2","Cpa3","Mcpt4","Mcpt8"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

Seurat::FeaturePlot(sobj, features =c("Plbd1","Cd209a", "Mgl2","Cd74"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

Seurat::FeaturePlot(sobj, features =c("Tpsb2", "Tpsab1", "Cpa3", "Kit","Hdc","Cma1","Ms4a2","Fcer1a"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)

Seurat::FeaturePlot(sobj, features =c("Mfge8","Cd207","H2-M2","Epcam","Pxdc1","Cd74"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, ncol=3)


Seurat::FeaturePlot(sobj, features =c("H2-Ab1"), reduction = name2D, cols = aquarius::color_gene, pt.size=1)

Seurat::FeaturePlot(sobj, features =c("percent.mt"), reduction = name2D, cols = aquarius::color_gene, pt.size=1)

Seurat::FeaturePlot(sobj, features =c("Mrc1"), reduction = name2D, cols = aquarius::color_gene, pt.size=1, split.by="sample_type")

Seurat::FeaturePlot(sobj, features =c("Postn"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, split.by="sample_type")

Seurat::FeaturePlot(sobj, features =c("Cxcl1"), reduction = name2D, cols = aquarius::color_gene, pt.size=0.1, split.by="sample_type")

Seurat::Idents(sobj) = sobj$IC_cluster_type

Seurat::VlnPlot(subset(sobj, idents = "Macrophages"), features =c("Tgfb1"), pt.size=0.1, split.by="sample_type", group.by="sample_type")
```

```{r Mrc1_expression_vln_plot, fig.width = 8, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$IC_cluster_type

sobj$cluster_type = factor(sobj$IC_cluster_type, levels = c("T cells","NK cells","Mast cells","Dendritic cells","Macrophages","Langerhans cells"))

Seurat::VlnPlot(subset(sobj, idents = "Macrophages"), features = c("Mrc1"), split.by= "sample_type", group.by ="IC_cluster_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r Spp1_expression_vln_plot, fig.width = 8, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$IC_cluster_type

sobj$cluster_type = factor(sobj$IC_cluster_type, levels = c("T cells","NK cells","Mast cells","Dendritic cells","Macrophages","Langerhans cells"))

Seurat::VlnPlot(subset(sobj, idents = "Macrophages"), features = c("Spp1"), split.by= "sample_type", group.by ="IC_cluster_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r Trem2_expression_vln_plot, fig.width = 8, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$IC_cluster_type

sobj$cluster_type = factor(sobj$IC_cluster_type, levels = c("T cells","NK cells","Mast cells","Dendritic cells","Macrophages","Langerhans cells"))

Seurat::VlnPlot(subset(sobj, idents = "Macrophages"), features = c("Trem2"), split.by= "sample_type", group.by ="IC_cluster_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r tgfb1_expression, fig.width = 22, fig.height = 7}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "Tgfb1",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                 name = "Expression level") +
  # ggplot2::theme(legend.key.height = unit(5,"mm"),
  #                legend.key.width = unit(5,"mm"),
  #                legend.title = element_text(size = 20),
  #                legend.text = element_text(size = 20)) +
  ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 2)
```

# Differential expression

```{r split_object}

sobj$condition_type = paste0(sobj$IC_cluster_type, "_",sobj$sample_type)
Seurat::Idents(sobj) = sobj$condition_type

```


```{r diff_expression_macrophages}
markP365 = Seurat::FindMarkers(sobj, ident.1 = c("Macrophages_flfl_cNFs_P365"), ident.2 = c("Macrophages_ctrl_HS_P365","Macrophages_ctrl_HS_P90")) %>%
  as.data.frame()  %>%
  dplyr::filter(p_val_adj < 0.05)

markP90_cNFs_HLS = Seurat::FindMarkers(sobj, ident.1 = c("Macrophages_flfl_cNFs_P90"), ident.2 = c("Macrophages_flfl_HLS_P90","Macrophages_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) 

markP90_cNFs_HS = Seurat::FindMarkers(sobj, ident.1 = c("Macrophages_flfl_cNFs_P90"), ident.2 = c("Macrophages_ctrl_HS_P90","Macrophages_ctrl_HS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) 

markP90_cNFs_all_HS_HLS = Seurat::FindMarkers(sobj, ident.1 = c("Macrophages_flfl_cNFs_P90"), ident.2 = c("Macrophages_ctrl_HS_P90","Macrophages_ctrl_HS_P365", "Macrophages_flfl_HLS_P90","Macrophages_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) 


markP365_cNFs_all_HS_HLS = Seurat::FindMarkers(sobj, ident.1 = c("Macrophages_flfl_cNFs_P365"), ident.2 = c("Macrophages_ctrl_HS_P90","Macrophages_ctrl_HS_P365", "Macrophages_flfl_HLS_P90","Macrophages_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) 

```

```{r diff_expression_dendritic_cells}
markP365 = Seurat::FindMarkers(sobj, ident.1 = c("Dendritic cells_flfl_cNFs_P365"), ident.2 = c( "Dendritic cells_flfl_HLS_P365")) %>%
  as.data.frame()  %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0)

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("Dendritic cells_flfl_cNFs_P90"), ident.2 = c("Dendritic cells_ctrl_HS_P90","Dendritic cells_flfl_HLS_P90")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) 
# %>%
  # dplyr::filter(avg_logFC > 0)
```

```{r cluster_ID_markers_dotplot}
Seurat::Idents(sobj) = sobj$IC_cluster_type

sobj$IC_cluster_type = factor(sobj$IC_cluster_type, levels = c("T cells","NK cells","Mast cells","Dendritic cells","Macrophages","Langerhans cells"))

Seurat::DotPlot(sobj,
                features = c("Cd3e","Klrk1","Nkg7","Ncr1","Kit","Cd209a","Lyz2","Adgre1","Epcam","Cd207"),
                group.by = "IC_cluster_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)


```



# R Session

```{r sessioninfo, echo = FALSE, fold_output = TRUE}
sessionInfo()
```

