---
title: "Analysis - immune cells - microenvironment datasets"
subtitle: "Zoom in immune cells - analysis"
author: "Pernelle"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: show
    code_download: true
    toc: true
    toc_float: true
    number_sections: false
---

<style>
body {
text-align: justify}
</style>

```{r clean, echo = FALSE}
rm(list = ls())
```

<!-- Automatically computes and prints in the output the running time for any code chunk -->
```{r, echo=FALSE}
# https://github.com/rstudio/rmarkdown/issues/1453
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (isFALSE(options[[paste0("fold_", type)]])) return(res)
    
    paste0(
      "<details><summary>", "show", "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot"),
  time_it = local({
    now = NULL
    function(before, options) {
      if (options$time_it) {
        if (before) {
          now <= Sys.time()
        } else {
          res = difftime(Sys.time(), now, units = "secs")
          paste("(Time to run :", round(res, digits = 2), "s)")
        }
      }
    }
  })
)
```

<!-- Set default parameters for all chunks -->
```{r, setup, include = FALSE}
set.seed(1337L)
knitr::opts_chunk$set(echo = TRUE, # display code
                      # display chunk output
                      message = FALSE,
                      warning = FALSE,
                      fold_output = FALSE, # usefull for sessionInfo()
                      fold_plot = FALSE,
                      
                      # figure settings
                      fig.align = 'center',
                      fig.width = 20,
                      fig.height = 15,
                      
                      # something about seed, chunk and Rmarkdown compilation
                      # https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script
                      # cache = TRUE,
                      cache.lazy = FALSE, 
                      
                      # add runtime after chunk
                      time_it = FALSE)
```


```{r library}
library(dplyr)
library(patchwork)
library(ggplot2)
library(org.Mm.eg.db)
library(ComplexHeatmap)
```


# Preparation

In this section, we set the global settings of the analysis. We will store data there :

```{r out_dir}
save_name = "VC"
out_dir = "."
```


We load the dataset :

```{r load_sobj}
sobj = readRDS(paste0(out_dir, "/../6_vascular_cells_annotation/","VC_sobj.rds"))
sobj
```

and sample information :

```{r load_sample_info}
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "env_metadata_sample_info.rds"))
sample_info
```

This is the projection of interest :

```{r name2D}
name2D = "harmony_43_umap"
```

We visualize clusters :


```{r clustering, fig.width = 6, fig.height = 4}
VC_markers = list("Pericytes" = c("Rgs5","Kcnj8","Pdgfrb"),
                  "Vascular endothelial cells" = c("Pecam1","Egfl7","Fabp4","Aqp1","Cdh5"),
                  "Lymphatic endothelial cells" = c("Lyve1","Prox1","Mmrn1","Fgl2","Fxyd6"),
                  "Smooth muscle cells" = c("Mfge8","Cd207","H2-M2","Epcam","Pxdc1","Cd74"))

# Not found in slot data:
# "Neutrophils" = c("S100a8", "S100a9","Retnlg"))

length(VC_markers)
color_markers_VC = c("blue4","firebrick4","seagreen4","orchid3")


names(color_markers_VC) = names(VC_markers)
Seurat::DimPlot(sobj, reduction = name2D, group.by ="VC_cluster_type", pt.size=0.1, cols = color_markers_VC) +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 1)
```

# Differential expression

```{r split_object}

sobj$condition_type = paste0(sobj$sample_type, "_",sobj$VC_cluster_type)
Seurat::Idents(sobj) = sobj$condition_type
```


```{r diff_expression_pericytes1}
mark_P90 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_cNFs_P90_Pericytes"), ident.2 = c("flfl_HLS_P90_Pericytes")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::arrange(avg_logFC)

mark_P365 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_HLS_P365_Pericytes"), ident.2 = c("flfl_cNFs_P365_Pericytes")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val < 0.05) %>%
  dplyr::arrange(avg_logFC)

Seurat::FeaturePlot(sobj, features =c("Tnc","Cxcl5","Cxcl3","Ccl2","Postn","Ngf"),reduction = name2D, cols = aquarius::color_gene, pt.size=0.5, split.by = "sample_type")

Seurat::FeaturePlot(sobj, features =c("Calcrl","Piezo2","Adamts2"),reduction = name2D, cols = aquarius::color_gene, pt.size=0.5, split.by = "sample_type")

Seurat::FeaturePlot(sobj, features =c("Adam12","Slit3","Ngf","Il11"),reduction = name2D, cols = aquarius::color_gene, pt.size=0.5, split.by = "sample_type")
```


```{r scores_of_interest, fig.width = 11, fig.height = 7}
Col_genes = c("Col1a1", "Col1a2","Col2a1","Col3a1","Col4a1","Col4a2","Col4a3", "Col4a4","Col4a5","Col4a6","Col5a1","Col5a2","Col5a3","Col5a4","Col6a1","Col6a2","Col6a3", "Col6a4","Col6a5","Col6a6","Col7a1","Col8a1", "Col8a2","Col9a1", "Col9a2","Col9a3","Col10a1","Col11a1", "Col11a2","Col11a3","Col12a1","Col13a1","Col14a1","Col15a1","Col16a1","Col17a1","Col18a1","Col19a1","Col20a1","Col21a1","Col22a1","Col23a1","Col24a1","Col25a1","Col26a1","Col27a1","Col28a1")

sobj$Col_score = Seurat::AddModuleScore(sobj, features = list(Col_genes))$Cluster1

Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::VlnPlot(sobj, features = c("Col_score"), split.by= "sample_type", group.by ="VC_cluster_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r collagen_score_calcul, fig.width = 22, fig.height = 7}
ECM_genes = c("Col1a1","Col1a2","Col3a1","Tgfbi","Mmp2","Loxl2","Fn1","Tnc","Postn","Acta2")

sobj$ECM_score = Seurat::AddModuleScore(sobj, features = list(ECM_genes))$Cluster1
```

```{r collagen_score_vln_plot, fig.width = 22, fig.height = 7}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::VlnPlot(sobj, features = c("ECM_score"), split.by= "sample_type", group.by ="VC_cluster_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r collagen_score_feature_plot_split, fig.width = 22, fig.height = 7}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "ECM_score",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                 name = "Expression level") +
  # ggplot2::theme(legend.key.height = unit(5,"mm"),
  #                legend.key.width = unit(5,"mm"),
  #                legend.title = element_text(size = 20),
  #                legend.text = element_text(size = 20)) +
  ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 3)
```

#ECM related genes

```{r ECM_proteins}
library(readxl)
ECM_proteins = read_excel("/shared/projects/nf1_scrnaseq_r/cnfs_dvpt/scRNAseq_Tom_cells/6_analyse/Mm_Matrisome_Masterlist_Naba et al_2012.xlsx")
```

```{r diff_expression_pericytes}
sobj$condition_type = paste0(sobj$sample_type, "_",sobj$VC_cluster_type)
Seurat::Idents(sobj) = sobj$condition_type

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_cNFs_P90_Pericytes"), ident.2 = c("flfl_HLS_P90_Pericytes")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::arrange(avg_logFC)

markP365 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_HLS_P365_Pericytes"), ident.2 = c("flfl_cNFs_P365_Pericytes")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val < 0.05) %>%
  dplyr::arrange(avg_logFC)
```

```{r heatmap_set_genes_Pericytes, fig.width = 22, fig.height = 6}
all_genes = sobj@assays[["RNA"]]@counts %>% rownames()

proteoglycans = ECM_proteins[ECM_proteins$'Matrisome Category'== "Proteoglycans", ] 
proteoglycansP90 = intersect(proteoglycans$'Gene Symbol', rownames(markP90))
proteoglycansP365 = intersect(proteoglycans$'Gene Symbol', rownames(markP365))
proteoglycans = unique(c(proteoglycansP90,proteoglycansP365))

ECM_glycoproteins = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Glycoproteins", ] 
ECM_glycoproteinsP90 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP90))
ECM_glycoproteinsP365 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP365))
ECM_glycoproteins = unique(c(ECM_glycoproteinsP90,ECM_glycoproteinsP365))

ECM_regulators = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Regulators", ] 
ECM_regulatorsP90 = intersect(ECM_regulators$'Gene Symbol', rownames(markP90))
ECM_regulatorsP365 = intersect(ECM_regulators$'Gene Symbol', rownames(markP365))
ECM_regulators = unique(c(ECM_regulatorsP90,ECM_regulatorsP365))

ECM_aff_prot = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM-affiliated Proteins", ] 
ECM_aff_protP90 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP90))
ECM_aff_protP365 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP365))
ECM_aff_prot = unique(c(ECM_aff_protP90,ECM_aff_protP365))

ECM_sec_factors = ECM_proteins[ECM_proteins$'Matrisome Category'== "Secreted factors", ] 
ECM_sec_factorsP90 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP90))
ECM_sec_factorsP365 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP365))
ECM_sec_factors = unique(c(ECM_sec_factorsP90,ECM_sec_factorsP365))
```


```{r dotplot_Pericytes, fig.width = 45, fig.height = 14}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))


Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::DotPlot(subset(sobj,idents = c("Pericytes")),
                features = c(ECM_glycoproteins, proteoglycans, ECM_aff_prot, ECM_sec_factors, ECM_regulators),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)
```

### ECM related genes

```{r diff_expression_VEC}
sobj$condition_type = paste0(sobj$sample_type, "_",sobj$VC_cluster_type)
Seurat::Idents(sobj) = sobj$condition_type

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_cNFs_P90_Vascular endothelial cells"), ident.2 = c("flfl_HLS_P90_Vascular endothelial cells")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::arrange(avg_logFC)

markP365 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_HLS_P365_Vascular endothelial cells"), ident.2 = c("flfl_cNFs_P365_Vascular endothelial cells")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val < 0.05) %>%
  dplyr::arrange(avg_logFC)
```

```{r heatmap_set_genes_VEC, fig.width = 22, fig.height = 6}

all_genes = sobj@assays[["RNA"]]@counts %>% rownames()

proteoglycans = ECM_proteins[ECM_proteins$'Matrisome Category'== "Proteoglycans", ] 
proteoglycansP90 = intersect(proteoglycans$'Gene Symbol', rownames(markP90))
proteoglycansP365 = intersect(proteoglycans$'Gene Symbol', rownames(markP365))
proteoglycans = unique(c(proteoglycansP90,proteoglycansP365))

ECM_glycoproteins = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Glycoproteins", ] 
ECM_glycoproteinsP90 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP90))
ECM_glycoproteinsP365 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP365))
ECM_glycoproteins = unique(c(ECM_glycoproteinsP90,ECM_glycoproteinsP365))

ECM_regulators = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Regulators", ] 
ECM_regulatorsP90 = intersect(ECM_regulators$'Gene Symbol', rownames(markP90))
ECM_regulatorsP365 = intersect(ECM_regulators$'Gene Symbol', rownames(markP365))
ECM_regulators = unique(c(ECM_regulatorsP90,ECM_regulatorsP365))

ECM_aff_prot = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM-affiliated Proteins", ] 
ECM_aff_protP90 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP90))
ECM_aff_protP365 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP365))
ECM_aff_prot = unique(c(ECM_aff_protP90,ECM_aff_protP365))

ECM_sec_factors = ECM_proteins[ECM_proteins$'Matrisome Category'== "Secreted factors", ] 
ECM_sec_factorsP90 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP90))
ECM_sec_factorsP365 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP365))
ECM_sec_factors = unique(c(ECM_sec_factorsP90,ECM_sec_factorsP365))
```


```{r dotplot_VEC, fig.width = 45, fig.height = 14}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))


Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::DotPlot(subset(sobj,idents = c("Vascular endothelial cells")),
                features = c(ECM_glycoproteins, proteoglycans, ECM_aff_prot, ECM_sec_factors, ECM_regulators),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)
```

### ECM related genes - Lymphatic endothelial cells

```{r diff_expression_LEC}
sobj$condition_type = paste0(sobj$sample_type, "_",sobj$VC_cluster_type)
Seurat::Idents(sobj) = sobj$condition_type

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_cNFs_P90_Lymphatic endothelial cells"), ident.2 = c("flfl_HLS_P90_Lymphatic endothelial cells")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::arrange(avg_logFC)

markP365 = Seurat::FindMarkers(sobj, ident.1 = c("flfl_HLS_P365_Lymphatic endothelial cells"), ident.2 = c("flfl_cNFs_P365_Lymphatic endothelial cells")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val < 0.05) %>%
  dplyr::arrange(avg_logFC)
```

```{r heatmap_set_genes_LEC, fig.width = 22, fig.height = 6}

all_genes = sobj@assays[["RNA"]]@counts %>% rownames()

proteoglycans = ECM_proteins[ECM_proteins$'Matrisome Category'== "Proteoglycans", ] 
proteoglycansP90 = intersect(proteoglycans$'Gene Symbol', rownames(markP90))
proteoglycansP365 = intersect(proteoglycans$'Gene Symbol', rownames(markP365))
proteoglycans = unique(c(proteoglycansP90,proteoglycansP365))

ECM_glycoproteins = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Glycoproteins", ] 
ECM_glycoproteinsP90 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP90))
ECM_glycoproteinsP365 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP365))
ECM_glycoproteins = unique(c(ECM_glycoproteinsP90,ECM_glycoproteinsP365))

ECM_regulators = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Regulators", ] 
ECM_regulatorsP90 = intersect(ECM_regulators$'Gene Symbol', rownames(markP90))
ECM_regulatorsP365 = intersect(ECM_regulators$'Gene Symbol', rownames(markP365))
ECM_regulators = unique(c(ECM_regulatorsP90,ECM_regulatorsP365))

ECM_aff_prot = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM-affiliated Proteins", ] 
ECM_aff_protP90 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP90))
ECM_aff_protP365 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP365))
ECM_aff_prot = unique(c(ECM_aff_protP90,ECM_aff_protP365))

ECM_sec_factors = ECM_proteins[ECM_proteins$'Matrisome Category'== "Secreted factors", ] 
ECM_sec_factorsP90 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP90))
ECM_sec_factorsP365 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP365))
ECM_sec_factors = unique(c(ECM_sec_factorsP90,ECM_sec_factorsP365))
```


```{r dotplot_LEC, fig.width = 45, fig.height = 14}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))


Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::DotPlot(subset(sobj,idents = c("Lymphatic endothelial cells")),
                features = c(ECM_glycoproteins, proteoglycans, ECM_aff_prot, ECM_sec_factors, ECM_regulators),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)
```


```{r dotplot_VC_markers, fig.width = 18, fig.height = 7.5}
Seurat::Idents(sobj) = sobj$VC_cluster_type
sobj$VC_cluster_type = factor(sobj$VC_cluster_type, levels = c("Pericytes","Vascular endothelial cells","Lymphatic endothelial cells"))

Seurat::DotPlot(sobj,
                features = c("Fxyd6","Fgl2","Mmrn1","Prox1","Lyve1","Cdh5","Pecam1","Egfl7","Aqp1","Fabp4","Ndufa4l2","Pdgfrb","Notch3","Rgs5"),
                group.by = "VC_cluster_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.4)
```

```{r dotplot_interesting_genes, fig.width = 15, fig.height = 12}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))
# subsobj1 = subset(sobj, idents = c("ctrl_HS_P90","ctrl_HS_P365"), invert = TRUE)
# subsobj1$sample_type = factor(subsobj1$sample_type, levels = c("flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365"))

Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::DotPlot(subset(sobj,idents = c("Pericytes")),
                features = c("Robo1","Il11","Adam12","Ccl7","Ccl2","Cxcl5","Cxcl3","Cxcl2","Postn","Tnc"),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.4)
```

```{r dotplot_ECM_genes, fig.width = 25, fig.height = 12}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))
# subsobj1 = subset(sobj, idents = c("ctrl_HS_P90","ctrl_HS_P365"), invert = TRUE)
# subsobj1$sample_type = factor(subsobj1$sample_type, levels = c("flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365"))

Seurat::Idents(sobj) = sobj$VC_cluster_type
Seurat::DotPlot(subset(sobj,idents = c("Pericytes")),
                features = c("Adamts9","Adamts1","Plau","Mmp14","Loxl2","Cd109","Adamts2","Adam12","Sema6d","Sdc1","Plxdc2","Anxa5","Tnc","Slit3","Postn","Nid1","Lamc1","Lamb1","Lama4","Lama2","Fbn1","Aebp1"),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.4)
```

```{r marker_prolif, fig.width = 14, fig.height = 8}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "Top2a",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                   name = "Expression level") +
    # ggplot2::theme(legend.key.height = unit(5,"mm"),
    #                legend.key.width = unit(5,"mm"),
    #                legend.title = element_text(size = 20),
    #                legend.text = element_text(size = 20)) +
    ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 3)
```

```{r diff_expression_wilcoxon}

Seurat::Idents(sobj) = sobj$VC_cluster_type
sobj$condition_VC = paste0(sobj$VC_cluster_type, "_",sobj$sample_type)
Seurat::Idents(sobj) = sobj$condition_VC


#mark_P365 = Seurat::FindMarkers(sobj, ident.1 = c("Pericytes_flfl_HLS_P365"), ident.2 = #c("Pericytes_flfl_HLS_P365")) %>%
#  as.data.frame() %>%
#  dplyr::filter(p_val_adj < 0.05) %>%
# dplyr::arrange(avg_logFC)


#mark_P365 = mark_P365 %>%
 # dplyr::filter(row.names(mark_P365) %in% Col_genes) %>%
 # dplyr::arrange(row.names(mark_P365))


df = data.frame(A = c("Pericytes_flfl_HLS_P365","Vascular endothelial cells_flfl_HLS_P365","Lymphatic endothelial cells_flfl_HLS_P365","Pericytes_flfl_HLS_P90","Vascular endothelial cells_flfl_HLS_P90","Lymphatic endothelial cells_flfl_HLS_P90"), B = c("Pericytes_ctrl_HS_P365","Vascular endothelial cells_ctrl_HS_P365","Lymphatic endothelial cells_ctrl_HS_P365","Pericytes_ctrl_HS_P90","Vascular endothelial cells_ctrl_HS_P90","Lymphatic endothelial cells_ctrl_HS_P90"))

lapply(row.names(df), FUN = function(id) {
  g1 = as.character(df[id,"A"])
  g2 = as.character(df[id,"B"])
  diff_means = round(mean(sobj$Col_score[sobj$condition_VC == g1]) - mean(sobj$Col_score[sobj$condition_VC == g2]), 3)
  DE = Seurat::FindMarkers(sobj, ident.1 = g1, ident.2 = g2) %>%
    as.data.frame() %>%
    dplyr::filter(p_val_adj < 0.05)
  DE = DE %>% dplyr::filter(row.names(DE) %in% Col_genes)
  test = t.test(sobj$Col_score[sobj$condition_VC == g1],
                sobj$Col_score[sobj$condition_VC == g2])
  pvalue = round(test$p.value, 4)
  output = c(g1, g2, diff_means, pvalue, row.names(DE), DE$avg_logFC)
  return(output)})
```



# R Session

```{r sessioninfo, echo = FALSE, fold_output = TRUE}
sessionInfo()
```

