---
title: "ECM genes"
subtitle: "Analysis heatmaps + violin plots"
author: "Pernelle"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: show
    code_download: true
    toc: true
    toc_float: true
    number_sections: false
---

<style>
body {
text-align: justify}
</style>

```{r clean, echo = FALSE}
rm(list = ls())
```

<!-- Automatically computes and prints in the output the running time for any code chunk -->
```{r, echo=FALSE}
# https://github.com/rstudio/rmarkdown/issues/1453
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (isFALSE(options[[paste0("fold_", type)]])) return(res)
    
    paste0(
      "<details><summary>", "show", "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot"),
  time_it = local({
    now = NULL
    function(before, options) {
      if (options$time_it) {
        if (before) {
          now <= Sys.time()
        } else {
          res = difftime(Sys.time(), now, units = "secs")
          paste("(Time to run :", round(res, digits = 2), "s)")
        }
      }
    }
  })
)
```

<!-- Set default parameters for all chunks -->
```{r, setup, include = FALSE}
set.seed(1337L)
knitr::opts_chunk$set(echo = TRUE, # display code
                      # display chunk output
                      message = FALSE,
                      warning = FALSE,
                      fold_output = FALSE, # usefull for sessionInfo()
                      fold_plot = FALSE,
                      
                      # figure settings
                      fig.align = 'center',
                      fig.width = 20,
                      fig.height = 15,
                      
                      # something about seed, chunk and Rmarkdown compilation
                      # https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script
                      # cache = TRUE,
                      cache.lazy = FALSE, 
                      
                      # add runtime after chunk
                      time_it = FALSE)
```


```{r library}
library(dplyr)
library(patchwork)
library(ggplot2)
library(org.Mm.eg.db)
library(ComplexHeatmap)
```


# Preparation

In this section, we set the global settings of the analysis. We will store data there :

```{r out_dir}
save_name = "SC"
out_dir = "."
```


We load the dataset :

```{r load_sobj}
sobj = readRDS(paste0(out_dir, "/../5_annotation/", save_name, "_sobj.rds"))
sobj
```

and sample information :

```{r load_sample_info}
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_sample_info.rds"))
sample_info
```

This is the projection of interest :

```{r name2D}
name2D = "harmony_46_umap"
```

We load metadata :

```{r load_metadata}
color_markers = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_color_markers.rds"))
cell_markers = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_cell_markers.rds"))
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_sample_info.rds"))
```

We visualize clusters :

```{r clustering, fig.width = 12, fig.height = 8, eval = FALSE}
cell_markers_SCs_fin = list("Other nmSCs" = c("Sox10", "Plp1", "S100b", "Lgi4","Gap43","Ngfr","Scn7a"),
                            #"Subepidermal glia" = c("Aqp1","Plac9","Igfbp7","Ldlrad4","Apod","Ndnf","Ifi47","Gja1","Pcdh20","Fez1","Lyz2"),
                            "Subepidermal glia" = c("Gja1","Aqp1","Igfbp7","Fez1","Plac9"),
                            "Lanceolate glia" = c("Aqp1", "Homer2", "Npy","Cav1","Robo2","Cavin2"),
                            "Proliferating nmSCs" = c("Birc5","Top2a","Mki67","H1f1"),
                            "mSCs" = c("Mbp","Mpz","Pmp22"))
color_markers_SCs_fin = c("red4","darkorchid","olivedrab1","chocolate3","dodgerblue3")
names(color_markers_SCs_fin) = names(cell_markers_SCs_fin)

Seurat::DimPlot(sobj, reduction = name2D, group.by ="cluster_type_SCs", label = FALSE, cols = color_markers_SCs_fin, pt.size = 0.5) +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 0.8)
```


```{r annot_global, class.source = "fold-hide"}
cell_markers_SCs = list(
  "Myelinating schwann cells" = c("Sox10", "Plp1", "S100b", "Lgi4", "Mpz","Pmp22","Mal","Egr2"),
  "Non myelinating schwann cells" = c("Sox10", "Plp1", "S100b", "Lgi4","Gap43","Ngfr","Scn7a"),
  "NA" = c("Fabp4", "Ebf1", "Mast4", "Rgs5","Epcam"))

color_markers_SCs = aquarius::c30_palette[c(1:length(cell_markers))]
names(color_markers_SCs) = names(cell_markers_SCs)

Seurat::DimPlot(sobj, reduction = name2D, group.by ="cluster_type", label = FALSE, cols = color_markers, pt.size = 0.5) +
  Seurat::NoLegend() +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 0.8)
```

```{r collagen_score_calcul, fig.width = 22, fig.height = 7}
Col_genes = c("Col1a1", "Col1a2","Col2a1","Col3a1","Col4a1","Col4a2","Col4a3", "Col4a4","Col4a5","Col4a6","Col5a1","Col5a2","Col5a3","Col5a4","Col6a1","Col6a2","Col6a3", "Col6a4","Col6a5","Col6a6","Col7a1","Col8a1", "Col8a2","Col9a1", "Col9a2","Col9a3","Col10a1","Col11a1", "Col11a2","Col11a3","Col12a1","Col13a1","Col14a1","Col15a1","Col16a1","Col17a1","Col18a1","Col19a1","Col20a1","Col21a1","Col22a1","Col23a1","Col24a1","Col25a1","Col26a1","Col27a1","Col28a1")

sobj$Col_score = Seurat::AddModuleScore(sobj, features = list(Col_genes))$Cluster1
```


```{r collagen_score_vln_plot, fig.width = 22, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "Proliferating nmSCs", invert = TRUE), features = c("Col_score"), split.by= "sample_type", group.by ="cluster_type_SCs", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```


```{r collagen_score_feature_plot_split, fig.width = 22, fig.height = 7}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "Col_score",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                 name = "Expression level") +
  # ggplot2::theme(legend.key.height = unit(5,"mm"),
  #                legend.key.width = unit(5,"mm"),
  #                legend.title = element_text(size = 20),
  #                legend.text = element_text(size = 20)) +
  ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 3)
```

```{r collagen_score_calcul, fig.width = 22, fig.height = 7}
ECM_genes = c("Col1a1","Col1a2","Col3a1","Tgfbi","Mmp2","Loxl2","Fn1","Tnc","Postn","Acta2")

sobj$ECM_score = Seurat::AddModuleScore(sobj, features = list(ECM_genes))$Cluster1
```

```{r collagen_score_vln_plot, fig.width = 22, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "Proliferating nmSCs", invert = TRUE), features = c("ECM_score"), split.by= "sample_type", group.by ="cluster_type_SCs", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```

```{r collagen_score_feature_plot_split, fig.width = 22, fig.height = 7}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "ECM_score",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                 name = "Expression level") +
  # ggplot2::theme(legend.key.height = unit(5,"mm"),
  #                legend.key.width = unit(5,"mm"),
  #                legend.title = element_text(size = 20),
  #                legend.text = element_text(size = 20)) +
  ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 3)
```

```{r laminin_score_calcul, fig.width = 22, fig.height = 7}
Lam_genes = c("Lamc2", "Lamc1","Lamb3","Lama5","Lamc3","Lama2","Lama4", "Lamb2","Lamb1","Lama1","Lama3")

sobj$Lam_score = Seurat::AddModuleScore(sobj, features = list(Lam_genes))$Cluster1
```


```{r laminin_score_vln_plot, fig.width = 22, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "Proliferating nmSCs", invert = TRUE), features = c("Lam_score"), split.by= "sample_type", group.by ="cluster_type_SCs", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```


```{r laminin_score_feature_plot_split, fig.width = 22, fig.height = 7}
plot_list = aquarius::plot_split_dimred(sobj,
                                        reduction = name2D,
                                        color_by = "Mmp14",
                                        split_by = "sample_type",
                                        bg_pt_size = 0.5,
                                        main_pt_size = 0.5)

plot_list = lapply(plot_list, FUN = function(one_plot) {
  one_plot = one_plot +
    ggplot2::scale_color_gradientn(colors = aquarius::color_gene,
                                 name = "Expression level") +
  # ggplot2::theme(legend.key.height = unit(5,"mm"),
  #                legend.key.width = unit(5,"mm"),
  #                legend.title = element_text(size = 20),
  #                legend.text = element_text(size = 20)) +
  ggplot2::theme(aspect.ratio = 0.8)
  return(one_plot)
})

names(plot_list) = levels(sobj$sample_type)
plot_list = plot_list[c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365")]
patchwork::wrap_plots(plot_list, ncol = 3)
```

### Heatmap

```{r ECM_proteins}
library(readxl)
ECM_proteins = read_excel("/home/aurelien/Bureau/scRNAseq_Tom_cells/6_analyse/Mm_Matrisome_Masterlist_Naba et al_2012.xlsx")
```

### Heatmap in SG - ECM genes

```{r split_object_SG}
sobj$condition_SCs = paste0(sobj$cluster_type_SCs, "_",sobj$sample_type)
Seurat::Idents(sobj) = sobj$condition_SCs

markP365 = Seurat::FindMarkers(sobj, ident.1 = c("Subepidermal glia_flfl_cNFs_P365"), ident.2 = c("Subepidermal glia_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0) 

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("Subepidermal glia_flfl_cNFs_P90"), ident.2 = c("Subepidermal glia_flfl_HLS_P90")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0) 
```


```{r heatmap_set_sobj_SG, fig.width = 22, fig.height = 6}
Seurat::Idents(sobj) = sobj$cluster_type_SCs
subsobj_HM = subset(sobj, idents = "Subepidermal glia")

subsobj_HM$sample_type = factor(subsobj_HM$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365","ctrl_HS_P365"))
```


```{r heatmap_set_genes_SG, fig.width = 22, fig.height = 6}
all_genes = sobj@assays[["RNA"]]@counts %>% rownames()

proteoglycans = ECM_proteins[ECM_proteins$'Matrisome Category'== "Proteoglycans", ] 
proteoglycansP90 = intersect(proteoglycans$'Gene Symbol', rownames(markP90))
proteoglycansP365 = intersect(proteoglycans$'Gene Symbol', rownames(markP365))
proteoglycans = unique(c(proteoglycansP90,proteoglycansP365))

ECM_glycoproteins = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Glycoproteins", ] 
ECM_glycoproteinsP90 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP90))
ECM_glycoproteinsP365 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP365))
ECM_glycoproteins = unique(c(ECM_glycoproteinsP90,ECM_glycoproteinsP365))

ECM_regulators = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Regulators", ] 
ECM_regulatorsP90 = intersect(ECM_regulators$'Gene Symbol', rownames(markP90))
ECM_regulatorsP365 = intersect(ECM_regulators$'Gene Symbol', rownames(markP365))
ECM_regulators = unique(c(ECM_regulatorsP90,ECM_regulatorsP365))

ECM_aff_prot = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM-affiliated Proteins", ] 
ECM_aff_protP90 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP90))
ECM_aff_protP365 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP365))
ECM_aff_prot = unique(c(ECM_aff_protP90,ECM_aff_protP365))

ECM_sec_factors = ECM_proteins[ECM_proteins$'Matrisome Category'== "Secreted factors", ] 
ECM_sec_factorsP90 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP90))
ECM_sec_factorsP365 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP365))
ECM_sec_factors = unique(c(ECM_sec_factorsP90,ECM_sec_factorsP365))

genes_heatmap = list(group01 = proteoglycans, 
                     group02 = ECM_glycoproteins,
                     group03 = ECM_aff_prot,
                     group04 = ECM_sec_factors,
                     group05 = ECM_regulators)


features_group = sapply(c(1:length(genes_heatmap)),
                        FUN = function(i) {
                          rep(x = names(genes_heatmap)[i],
                              length = length(genes_heatmap[[i]]))}) %>% unlist() %>% as.vector()
features = unique(unlist(genes_heatmap))

```

```{r heatmap_set_matrix_SG, fig.width = 22, fig.height = 6}

mat_expression = Seurat::GetAssayData(subsobj_HM, assay = "RNA", slot = "data")
mat_expression = mat_expression[features, ]
mat_expression = Matrix::t(mat_expression)
mat_expression = dynutils::scale_quantile(mat_expression) # between 0 and 1
mat_expression = Matrix::t(mat_expression)
dim(mat_expression)
```

```{r heatmap_set_annotation_SG, fig.width = 22, fig.height = 6}
list_colors = list()
list_colors[["expression"]] = aquarius::color_cnv

# change colors !!
list_colors[["sample_type"]] = c(ctrl_HS_P90 = "white",
                                 flfl_HLS_P90 = "white",
                                 flfl_cNFs_P90 = "white",
                                 flfl_cNFs_P365 = "white",
                                 flfl_HLS_P365 = "white",
                                 ctrl_HS_P365 = "white")
list_colors[["sample_identifier"]] = setNames(nm = sample_info$sample_identifier,
                                              sample_info$color)
list_colors[["cell_cycle_phase"]] = aquarius::gg_color_hue(3)
names(list_colors[["cell_cycle_phase"]]) = c("G0 / G1", "G2M", "S")
list_colors[["percent_mito"]] = circlize::colorRamp2(breaks = seq(from = min(subsobj_HM$percent.mt),
                                                                  to = max(sobj$percent.mt),
                                                                  length.out = 9),
                                                     colors = RColorBrewer::brewer.pal(name = "Greys", n = 9))
list_colors[["nFeature_RNA"]] = circlize::colorRamp2(breaks = seq(from = min(subsobj_HM$nFeature_RNA),
                                                                  to = max(subsobj_HM$nFeature_RNA),
                                                                  length.out = 9),
                                                     colors = RColorBrewer::brewer.pal(name = "Greys", n = 9))
```

```{r heatmap_set_color_SG, fig.width = 22, fig.height = 6}
name_side = "right"
ha_top = HeatmapAnnotation(
  group = anno_block(gp = gpar(fill = list_colors[["sample_type"]]),
                     labels = sort(unique(subsobj_HM$sample_type))
                     ),
  sample_identifier = subsobj_HM$sample_identifier,
  col = list(sample_identifier = list_colors[["sample_identifier"]]),
  annotation_name_side = name_side)

ha_bottom = HeatmapAnnotation(
  percent_mito = subsobj_HM$percent.mt,
  nFeature_RNA = subsobj_HM$nFeature_RNA,
  # cell_cycle_phase = as.factor(subsobj_HM$Seurat.Phase) %>% `levels<-`(c("G0 / G1", "G2M", "S")),
  col = list(percent_mito = list_colors[["percent_mito"]],
             nFeature_RNA = list_colors[["nFeature_RNA"]]),
             # cell_cycle_phase = list_colors[["cell_cycle_phase"]]),
  annotation_name_side = name_side)
```

```{r heatmap_set_SG, fig.width = 22, fig.height = 6}
ht = ComplexHeatmap::Heatmap(
  as.matrix(mat_expression),
  # Expression colors
  col = list_colors[["expression"]],
  heatmap_legend_param = list(title = "Expression", at = c(0, 1), 
                              labels = c("low", "high")),
  # Annotation
  top_annotation = ha_top,
  bottom_annotation = ha_bottom,
  # Cells grouping
  column_split = subsobj_HM$sample_type,
  column_gap = unit(2, "mm"),
  column_title = NULL,
  # Cells order
  column_order = order(subsobj_HM$sample_type),
  cluster_columns = FALSE, #faire un clustering des cellules
  show_column_dend = FALSE, #montrer l'arbre du clustering (dendrogramme)
  # Cells label
  show_column_names = FALSE,
  # Gene grouping
  row_split = features_group,
  row_gap = unit(2, "mm"),
  row_title = NULL,
  cluster_rows = FALSE, #clusteriser les gènes à peu près co-exprimés
  show_row_dend = FALSE, #montrer l'arbre du clustering (dendrogramme)
  # Gene labels
  row_labels = features,
  show_row_names = TRUE,
  row_names_side = name_side,
  row_names_gp = grid::gpar(fontsize = 13), #customiser la taille du texte des noms des lignes
  # Visual aspect
  show_heatmap_legend = TRUE,
  border = TRUE,
  use_raster = FALSE)
```

```{r draw_heatmap_SG, fig.width = 22, fig.height = 15}
ComplexHeatmap::draw(ht, # legend_grouping = "original",
                     merge_legend = TRUE,
                     heatmap_legend_side = "bottom",
                     annotation_legend_side = "bottom")
```

```{r dotplot_SG_cluster, fig.width = 35, fig.height = 7.5}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

Seurat::Idents(sobj) = sobj$cluster_type_SCs
Seurat::DotPlot(subset(sobj,idents = c("Subepidermal glia")),
                features = c(ECM_glycoproteins, proteoglycans, ECM_aff_prot, ECM_sec_factors, ECM_regulators),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)

```

### Heatmap in other nmSCs - ECM genes

```{r split_object_other_nmSCs}
sobj$condition_SCs = paste0(sobj$cluster_type_SCs, "_",sobj$sample_type)
Seurat::Idents(sobj) = sobj$condition_SCs

markP365 = Seurat::FindMarkers(sobj, ident.1 = c("Other nmSCs_flfl_cNFs_P365"), ident.2 = c("Other nmSCs_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0) 

markP90 = Seurat::FindMarkers(sobj, ident.1 = c("Other nmSCs_flfl_cNFs_P90"), ident.2 = c("Other nmSCs_flfl_HLS_P90")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0) 
```


```{r heatmap_set_sobj_other_nmSCs, fig.width = 22, fig.height = 6}
Seurat::Idents(sobj) = sobj$cluster_type_SCs
subsobj_HM = subset(sobj, idents = "Other nmSCs")

subsobj_HM$sample_type = factor(subsobj_HM$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365","ctrl_HS_P365"))
```


```{r heatmap_set_genes_other_nmSCs, fig.width = 22, fig.height = 6}
all_genes = sobj@assays[["RNA"]]@counts %>% rownames()

proteoglycans = ECM_proteins[ECM_proteins$'Matrisome Category'== "Proteoglycans", ] 
proteoglycansP90 = intersect(proteoglycans$'Gene Symbol', rownames(markP90))
proteoglycansP365 = intersect(proteoglycans$'Gene Symbol', rownames(markP365))
proteoglycans = unique(c(proteoglycansP90,proteoglycansP365))

ECM_glycoproteins = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Glycoproteins", ] 
ECM_glycoproteinsP90 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP90))
ECM_glycoproteinsP365 = intersect(ECM_glycoproteins$'Gene Symbol', rownames(markP365))
ECM_glycoproteins = unique(c(ECM_glycoproteinsP90,ECM_glycoproteinsP365))

ECM_regulators = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM Regulators", ] 
ECM_regulatorsP90 = intersect(ECM_regulators$'Gene Symbol', rownames(markP90))
ECM_regulatorsP365 = intersect(ECM_regulators$'Gene Symbol', rownames(markP365))
ECM_regulators = unique(c(ECM_regulatorsP90,ECM_regulatorsP365))

ECM_aff_prot = ECM_proteins[ECM_proteins$'Matrisome Category'== "ECM-affiliated Proteins", ] 
ECM_aff_protP90 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP90))
ECM_aff_protP365 = intersect(ECM_aff_prot$'Gene Symbol', rownames(markP365))
ECM_aff_prot = unique(c(ECM_aff_protP90,ECM_aff_protP365))

ECM_sec_factors = ECM_proteins[ECM_proteins$'Matrisome Category'== "Secreted factors", ] 
ECM_sec_factorsP90 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP90))
ECM_sec_factorsP365 = intersect(ECM_sec_factors$'Gene Symbol', rownames(markP365))
ECM_sec_factors = unique(c(ECM_sec_factorsP90,ECM_sec_factorsP365))

genes_heatmap = list(group01 = proteoglycans, 
                     group02 = ECM_glycoproteins,
                     group03 = ECM_aff_prot,
                     group04 = ECM_sec_factors)


features_group = sapply(c(1:length(genes_heatmap)),
                        FUN = function(i) {
                          rep(x = names(genes_heatmap)[i],
                              length = length(genes_heatmap[[i]]))}) %>% unlist() %>% as.vector()
features = unique(unlist(genes_heatmap))

```

```{r heatmap_set_matrix_other_nmSCs, fig.width = 22, fig.height = 6}

mat_expression = Seurat::GetAssayData(subsobj_HM, assay = "RNA", slot = "data")
mat_expression = mat_expression[features, ]
mat_expression = Matrix::t(mat_expression)
mat_expression = dynutils::scale_quantile(mat_expression) # between 0 and 1
mat_expression = Matrix::t(mat_expression)
dim(mat_expression)
```

```{r heatmap_set_annotation_other_nmSCs, fig.width = 22, fig.height = 6}
list_colors = list()
list_colors[["expression"]] = aquarius::color_cnv

# change colors !!
list_colors[["sample_type"]] = c(ctrl_HS_P90 = "white",
                                 flfl_HLS_P90 = "white",
                                 flfl_cNFs_P90 = "white",
                                 flfl_cNFs_P365 = "white",
                                 flfl_HLS_P365 = "white",
                                 ctrl_HS_P365 = "white")
list_colors[["sample_identifier"]] = setNames(nm = sample_info$sample_identifier,
                                              sample_info$color)
list_colors[["cell_cycle_phase"]] = aquarius::gg_color_hue(3)
names(list_colors[["cell_cycle_phase"]]) = c("G0 / G1", "G2M", "S")
list_colors[["percent_mito"]] = circlize::colorRamp2(breaks = seq(from = min(subsobj_HM$percent.mt),
                                                                  to = max(sobj$percent.mt),
                                                                  length.out = 9),
                                                     colors = RColorBrewer::brewer.pal(name = "Greys", n = 9))
list_colors[["nFeature_RNA"]] = circlize::colorRamp2(breaks = seq(from = min(subsobj_HM$nFeature_RNA),
                                                                  to = max(subsobj_HM$nFeature_RNA),
                                                                  length.out = 9),
                                                     colors = RColorBrewer::brewer.pal(name = "Greys", n = 9))
```

```{r heatmap_set_color_other_nmSCs, fig.width = 22, fig.height = 6}
name_side = "right"
ha_top = HeatmapAnnotation(
  group = anno_block(gp = gpar(fill = list_colors[["sample_type"]]),
                     labels = sort(unique(subsobj_HM$sample_type))
                     ),
  sample_identifier = subsobj_HM$sample_identifier,
  col = list(sample_identifier = list_colors[["sample_identifier"]]),
  annotation_name_side = name_side)

ha_bottom = HeatmapAnnotation(
  percent_mito = subsobj_HM$percent.mt,
  nFeature_RNA = subsobj_HM$nFeature_RNA,
  # cell_cycle_phase = as.factor(subsobj_HM$Seurat.Phase) %>% `levels<-`(c("G0 / G1", "G2M", "S")),
  col = list(percent_mito = list_colors[["percent_mito"]],
             nFeature_RNA = list_colors[["nFeature_RNA"]]),
             # cell_cycle_phase = list_colors[["cell_cycle_phase"]]),
  annotation_name_side = name_side)
```

```{r heatmap_set_other_nmSCs, fig.width = 22, fig.height = 6}
ht = ComplexHeatmap::Heatmap(
  as.matrix(mat_expression),
  # Expression colors
  col = list_colors[["expression"]],
  heatmap_legend_param = list(title = "Expression", at = c(0, 1), 
                              labels = c("low", "high")),
  # Annotation
  top_annotation = ha_top,
  bottom_annotation = ha_bottom,
  # Cells grouping
  column_split = subsobj_HM$sample_type,
  column_gap = unit(2, "mm"),
  column_title = NULL,
  # Cells order
  column_order = order(subsobj_HM$sample_type),
  cluster_columns = FALSE, #faire un clustering des cellules
  show_column_dend = FALSE, #montrer l'arbre du clustering (dendrogramme)
  # Cells label
  show_column_names = FALSE,
  # Gene grouping
  row_split = features_group,
  row_gap = unit(2, "mm"),
  row_title = NULL,
  cluster_rows = FALSE, #clusteriser les gènes à peu près co-exprimés
  show_row_dend = FALSE, #montrer l'arbre du clustering (dendrogramme)
  # Gene labels
  row_labels = features,
  show_row_names = TRUE,
  row_names_side = name_side,
  row_names_gp = grid::gpar(fontsize = 13), #customiser la taille du texte des noms des lignes
  # Visual aspect
  show_heatmap_legend = TRUE,
  border = TRUE,
  use_raster = FALSE)
```

```{r draw_heatmap_other_nmSCs, fig.width = 22, fig.height = 15}
ComplexHeatmap::draw(ht, # legend_grouping = "original",
                     merge_legend = TRUE,
                     heatmap_legend_side = "bottom",
                     annotation_legend_side = "bottom")
```

```{r dotplot_other_nmSCs_cluster, fig.width = 25, fig.height = 7.5}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))
subsobj1 = subset(sobj, idents = c("ctrl_HS_P90","ctrl_HS_P365"), invert = TRUE)
subsobj1$sample_type = factor(subsobj1$sample_type, levels = c("flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365"))

Seurat::Idents(subsobj1) = subsobj1$cluster_type_SCs
Seurat::DotPlot(subset(subsobj1,idents = c("Other nmSCs")),
                features = c(ECM_glycoproteins, proteoglycans, ECM_aff_prot, ECM_sec_factors, ECM_regulators),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)

```

### VlnPlot Sum-up SG

```{r dotplot_SG_cluster_sum_up, fig.width = 25, fig.height = 7.5}
Seurat::Idents(sobj) = sobj$sample_type
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))
# subsobj1 = subset(sobj, idents = c("ctrl_HS_P90","ctrl_HS_P365"), invert = TRUE)
# subsobj1$sample_type = factor(subsobj1$sample_type, levels = c("flfl_HLS_P90","flfl_cNFs_P90","flfl_cNFs_P365","flfl_HLS_P365"))

Seurat::Idents(sobj) = sobj$cluster_type_SCs
Seurat::DotPlot(subset(sobj,idents = c("Subepidermal glia")),
                features = c("Abi3bp","Reln","Lgals1","Anxa5","Anxa1","Igfbp7" ,"Sparc","Serpine2","Adamtsl1","Itih5","Lamc1","Lamb1","Lama4","Postn","Nid1","Ltbp1","Matn2","Edil3","Anxa6","Bgn","Vcan","Thbs2","Pxdn","Fbln2","Agrn","Aebp1","Adam19","Adamts5","Loxl2","Mmp14","Mmp2","Pappa","Plod2","Tgfbi","Tnc"),
                group.by = "sample_type", dot.scale = 15) +
  ggplot2::scale_color_gradientn(colors = aquarius::color_gene) +
  ggplot2::theme(axis.title = element_blank(),
                 legend.key.height = unit(10,"mm"),
                 legend.key.width = unit(10,"mm"),
                 legend.title = element_text(size = 25),
                 legend.text = element_text(size = 25),
                 axis.text = element_text(size = 30),
                 axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(aspect.ratio = 0.3)
```

```{r Gvenn, fig.width = 25, fig.height = 7.5}
library(readxl)
ECM_proteins = read_excel("/home/aurelien/Bureau/scRNAseq_Tom_cells/6_analyse/Mm_Matrisome_Masterlist_Naba et al_2012.xlsx")



sobj$condition_SCs = paste0(sobj$cluster_type_SCs, "_",sobj$sample_type)
Seurat::Idents(sobj) = sobj$condition_SCs

markP365_other = Seurat::FindMarkers(sobj, ident.1 = c("Other nmSCs_flfl_cNFs_P365"), ident.2 = c("Other nmSCs_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0) 

markP90_other = Seurat::FindMarkers(sobj, ident.1 = c("Other nmSCs_flfl_cNFs_P90"), ident.2 = c("Other nmSCs_flfl_HLS_P90")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0)

markP90_SG = Seurat::FindMarkers(sobj, ident.1 = c("Subepidermal glia_flfl_cNFs_P90"), ident.2 = c("Subepidermal glia_flfl_HLS_P90")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0)

markP365_SG = Seurat::FindMarkers(sobj, ident.1 = c("Subepidermal glia_flfl_cNFs_P365"), ident.2 = c("Subepidermal glia_flfl_HLS_P365")) %>%
  as.data.frame() %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_logFC > 0)


ggvenn::ggvenn(list(P365_SG = intersect(ECM_proteins$'Gene Symbol', rownames(markP365_SG)),
                    P90_SG = intersect(ECM_proteins$'Gene Symbol', rownames(markP90_SG)),
                    P90_other =intersect(ECM_proteins$'Gene Symbol',  rownames(markP90_other)),
                    P365_other = intersect(ECM_proteins$'Gene Symbol', rownames(markP365_other))),
               text_size = 10, show_percentage = FALSE) +
  ggplot2::labs(title = "Comparison ECM genes between SG and other nmSCs") +
  ggplot2::theme(plot.title = element_text(hjust = 0.5, size = 20))
```

# R Session

```{r sessioninfo, echo = FALSE, fold_output = TRUE}
sessionInfo()
```