---
title: "MAPK genes"
subtitle: "Analysis heatmaps + violin plots"
author: "Pernelle"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: show
    code_download: true
    toc: true
    toc_float: true
    number_sections: false
---

<style>
body {
text-align: justify}
</style>

```{r clean, echo = FALSE}
rm(list = ls())
```

<!-- Automatically computes and prints in the output the running time for any code chunk -->
```{r, echo=FALSE}
# https://github.com/rstudio/rmarkdown/issues/1453
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (isFALSE(options[[paste0("fold_", type)]])) return(res)
    
    paste0(
      "<details><summary>", "show", "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot"),
  time_it = local({
    now = NULL
    function(before, options) {
      if (options$time_it) {
        if (before) {
          now <= Sys.time()
        } else {
          res = difftime(Sys.time(), now, units = "secs")
          paste("(Time to run :", round(res, digits = 2), "s)")
        }
      }
    }
  })
)
```

<!-- Set default parameters for all chunks -->
```{r, setup, include = FALSE}
set.seed(1337L)
knitr::opts_chunk$set(echo = TRUE, # display code
                      # display chunk output
                      message = FALSE,
                      warning = FALSE,
                      fold_output = FALSE, # usefull for sessionInfo()
                      fold_plot = FALSE,
                      
                      # figure settings
                      fig.align = 'center',
                      fig.width = 20,
                      fig.height = 15,
                      
                      # something about seed, chunk and Rmarkdown compilation
                      # https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script
                      # cache = TRUE,
                      cache.lazy = FALSE, 
                      
                      # add runtime after chunk
                      time_it = FALSE)
```


```{r library}
library(dplyr)
library(patchwork)
library(ggplot2)
library(org.Mm.eg.db)
library(ComplexHeatmap)
```


# Preparation

In this section, we set the global settings of the analysis. We will store data there :

```{r out_dir}
save_name = "SC"
out_dir = "."
```


We load the dataset :

```{r load_sobj}
sobj = readRDS(paste0(out_dir, "/../5_annotation/", save_name, "_sobj.rds"))
sobj
```

and sample information :

```{r load_sample_info}
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_sample_info.rds"))
sample_info
```

This is the projection of interest :

```{r name2D}
name2D = "harmony_46_umap"
```

We load metadata :

```{r load_metadata}
color_markers = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_color_markers.rds"))
cell_markers = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_cell_markers.rds"))
sample_info = readRDS(paste0(out_dir, "/../1_metadata/", "Tom_metadata_sample_info.rds"))
```

We visualize clusters :

```{r clustering, fig.width = 12, fig.height = 8, eval = FALSE}
cell_markers_SCs_fin = list("Other nmSCs" = c("Sox10", "Plp1", "S100b", "Lgi4","Gap43","Ngfr","Scn7a"),
                            #"Subepidermal glia" = c("Aqp1","Plac9","Igfbp7","Ldlrad4","Apod","Ndnf","Ifi47","Gja1","Pcdh20","Fez1","Lyz2"),
                            "Subepidermal glia" = c("Gja1","Aqp1","Igfbp7","Fez1","Plac9"),
                            "Lanceolate glia" = c("Aqp1", "Homer2", "Npy","Cav1","Robo2","Cavin2"),
                            "Proliferating nmSCs" = c("Birc5","Top2a","Mki67","H1f1"),
                            "mSCs" = c("Mbp","Mpz","Pmp22"))
color_markers_SCs_fin = c("red4","darkorchid","olivedrab1","chocolate3","dodgerblue3")
names(color_markers_SCs_fin) = names(cell_markers_SCs_fin)

Seurat::DimPlot(sobj, reduction = name2D, group.by ="cluster_type_SCs", label = FALSE, cols = color_markers_SCs_fin, pt.size = 0.5) +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 0.8)
```


```{r annot_global, class.source = "fold-hide"}
cell_markers_SCs = list(
  "Myelinating schwann cells" = c("Sox10", "Plp1", "S100b", "Lgi4", "Mpz","Pmp22","Mal","Egr2"),
  "Non myelinating schwann cells" = c("Sox10", "Plp1", "S100b", "Lgi4","Gap43","Ngfr","Scn7a"),
  "NA" = c("Fabp4", "Ebf1", "Mast4", "Rgs5","Epcam"))

color_markers_SCs = aquarius::c30_palette[c(1:length(cell_markers))]
names(color_markers_SCs) = names(cell_markers_SCs)

Seurat::DimPlot(sobj, reduction = name2D, group.by ="cluster_type", label = FALSE, cols = color_markers, pt.size = 0.5) +
  Seurat::NoLegend() +
  Seurat::NoAxes() +
  ggplot2::theme(aspect.ratio = 0.8)
```


```{r vln_plot_mapk_genes, fig.width =50, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "mSCs"), features = c("Sos1","Sos2","Rapgef1","Dusp6"), split.by= "sample_type", group.by ="cluster_type_SCs", cols = colors, pt.size = 0, ncol = 4)
```

```{r MAPK_pathway_activity, fig.width = 22, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "Proliferating nmSCs", invert = TRUE), features = "Dusp6",  group.by ="cluster_type_SCs", split.by = "sample_type", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```



```{r MAPK_score_calcul, fig.width = 22, fig.height = 7}
MAPK_genes = c("Spry2", "Spry4","Etv4","Etv5","Dusp4","Dusp5","Ccnd1", "Epha2","Epha4")

sobj$MAPK_score = Seurat::AddModuleScore(sobj, features = list(MAPK_genes))$Cluster1
```

```{r MAPK_score_vln_plot, fig.width = 22, fig.height = 7}
sobj$sample_type = factor(sobj$sample_type, levels = c("ctrl_HS_P90","flfl_HLS_P90","flfl_cNFs_P90","ctrl_HS_P365","flfl_HLS_P365","flfl_cNFs_P365"))

colors = c("purple2","orchid2","firebrick2","orange2", "chartreuse2","cadetblue2")

Seurat::Idents(sobj) = sobj$cluster_type_SCs

Seurat::VlnPlot(subset(sobj, idents = "Proliferating nmSCs", invert = TRUE), features = c("Sos2"), split.by= "sample_type", group.by ="cluster_type_SCs", cols = colors, pt.size = 0, ncol =1)  + ggplot2::geom_boxplot(position = position_dodge(0.90), width=0.15, outlier.shape = NA, fatten = NULL) + ggplot2::stat_summary(fun=mean, geom="point", color="black", position = position_dodge(0.90), width=0.3)
```


# R Session

```{r sessioninfo, echo = FALSE, fold_output = TRUE}
sessionInfo()
```